name: dharmesh_widget_component
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  get: ^4.6.6
  animate_do: ^3.3.4
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^1.10.16
  get_storage: ^2.1.1
  image_picker: ^1.0.4
  uuid: ^4.0.0
  equatable: ^2.0.5
  swipe_to: ^1.0.6
  google_fonts: ^6.2.1
  o3d: ^1.1.1



  video_thumbnail: ^0.5.3
  clipboard: ^0.1.3
  dotted_border: ^2.1.0
  another_flushbar: ^1.12.30
  syncfusion_flutter_pdfviewer: ^26.1.42
  lottie: ^2.3.2
  flutter_svg: ^1.1.3
  shared_preferences: ^2.0.15
  permission_handler: ^11.3.1
  cached_network_image: ^3.3.1
  connectivity_plus: ^2.3.6
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  flutter_spinkit: ^5.2.0
  flutter_screenutil: ^5.9.0
  intl: ^0.19.0
  fpdart: ^1.1.0
  graphview: ^1.2.0
  country_picker: ^2.0.26
  msh_checkbox: ^2.0.1
  insta_image_viewer: ^1.0.4
  flutter_hooks: ^0.18.5+1
  file_picker: ^6.0.0
  fluttertoast: ^8.2.6
  boxy: ^2.0.5

  device_info_plus: ^10.0.1
  local_hero:
    git:
      url: https://github.com/mkobuolys/local_hero.git
      ref: mark-needs-paint-error-fix

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/profile/
    - assets/animation/
    - assets/images/
    - assets/icons/
    - assets/
